
/**
 * Creates an anti-aliased border around a distance-based shape.
 *
 * @param dist       Distance from the shape's center or origin.
 * @param borderSize Thickness of the border.
 * @param shapeSize  Radius or size of the shape's outer boundary.
 * @param edgeSmooth Width of the anti-aliasing transition.
 * @return           A mask value between 0.0 and 1.0.
 */
float borderShape(float dist, float borderSize, float shapeSize, float edgeSmooth) {
    float halfBorder = borderSize * 0.5;

    float outer = 1.0 - smoothstep(
        shapeSize + halfBorder - edgeSmooth,
        shapeSize + halfBorder,
        dist
    );

    float inner = smoothstep(
        shapeSize - halfBorder - edgeSmooth,
        shapeSize - halfBorder,
        dist
    );

    return outer * inner;
}

/**
 * Creates a filled, anti-aliased shape mask.
 *
 * @param dist       Distance from the shape's center or origin.
 * @param shapeSize  Radius or size of the shape's boundary.
 * @param edgeSmooth Width of the anti-aliasing transition.
 * @return           A mask value between 0.0 and 1.0.
 */
float filledShape(float dist, float shapeSize, float edgeSmooth) {
    return 1.0 - smoothstep(shapeSize - edgeSmooth, shapeSize, dist);
}

/**
 * Creates a filled shape with alternating stripes.
 *
 * @param dist           Distance from the shape's center or origin.
 * @param shapeSize      Radius or size of the shape's boundary.
 * @param stripeFrequency Number of stripe cycles per distance unit.
 * @param edgeSmooth     Width of the shape's anti-aliasing transition.
 * @param adjust         Phase offset that shifts the stripe pattern.
 * @return               A striped mask clipped to the shape boundary.
 */
float stripedShape(
    float dist,
    float shapeSize,
    float stripeFrequency,
    float edgeSmooth,
    float adjust
) {
    float baseShape = filledShape(dist, shapeSize, edgeSmooth);
    float stripes = step(0.5, fract(dist * stripeFrequency + adjust));

    return baseShape * stripes;
}

/**
 * Selects a shape rendering style.
 *
 * @param dist       Distance from the shape's center or origin.
 * @param style      Style selector: 0 = filled, 1 = bordered, 2 = striped.
 * @param shapeSize  Radius or size of the shape's boundary.
 * @param borderSize Thickness of the border; used by style 1.
 * @param stripeFreq Stripe frequency; used by style 2.
 * @param edgeSmooth Width of the anti-aliasing transition.
 * @param adjust     Phase offset for the stripe pattern.
 * @return           The mask generated by the selected style, or 0.0
 *                   if the style is unsupported.
 */
float variantShape(
    float dist,
    int style,
    float shapeSize,
    float borderSize,
    float stripeFreq,
    float edgeSmooth,
    float adjust
) {
    if (style == 0) {
        return filledShape(dist, shapeSize, edgeSmooth);
    } else if (style == 1) {
        return borderShape(dist, borderSize, shapeSize, edgeSmooth);
    } else if (style == 2) {
        return stripedShape(dist, shapeSize, stripeFreq, edgeSmooth, adjust);
    }

    return 0.0;
}

/**
 * Creates a filled shape using the default style.
 *
 * @param dist       Distance from the shape's center or origin.
 * @param shapeSize  Radius or size of the shape's boundary.
 * @param edgeSmooth Width of the anti-aliasing transition.
 * @return           A filled shape mask between 0.0 and 1.0.
 */
float variantShape(float dist, float shapeSize, float edgeSmooth) {
    return filledShape(dist, shapeSize, edgeSmooth);
}

/**
 * Creates a bordered shape using the default style.
 *
 * @param dist       Distance from the shape's center or origin.
 * @param shapeSize  Radius or size of the shape's outer boundary.
 * @param borderSize Thickness of the border.
 * @param edgeSmooth Width of the anti-aliasing transition.
 * @return           A bordered shape mask between 0.0 and 1.0.
 */
float variantShape(float dist, float shapeSize, float borderSize, float edgeSmooth) {
    return borderShape(dist, borderSize, shapeSize, edgeSmooth);
}

/**
 * Converts UV coordinates into a normalized angle.
 *
 * The angle is mapped to the range [0.0, 1.0], making it
 * useful for radial patterns and angular effects.
 *
 * @param uv 2D coordinate used to calculate the angle.
 * @return   Normalized angle in the range [0.0, 1.0].
 */
float getAngle(vec2 uv) {
    return atan(uv.y, uv.x) / (PI * 2.0) + 0.5;
}

/**
 * Calculates a signed distance field for an equilateral triangle.
 *
 * The triangle is centered around the origin and mirrored
 * across the Y axis to maintain left-right symmetry.
 *
 * @param uv 2D coordinate relative to the triangle's center.
 * @return   Signed distance approximation to the triangle boundary.
 */
float triangleField(vec2 uv) {
    uv.x = abs(uv.x);

    vec2 edgeNormal = vec2(0.866025, 0.5);

    float sides = dot(uv, edgeNormal);
    float bottom = -uv.y;

    return max(sides, bottom);
}

/**
 * Calculates the radial distance from the origin.
 *
 * @param uv 2D coordinate relative to the circle's center.
 * @return   Euclidean distance from the origin.
 */
float circleField(vec2 uv) {
    return length(uv);
}

/**
 * Calculates a square distance field using the maximum
 * absolute coordinate.
 *
 * @param uv 2D coordinate relative to the rectangle's center.
 * @return   Chebyshev distance from the origin.
 */
float rectangleField(vec2 uv) {
    return max(abs(uv.x), abs(uv.y));
}

/**
 * Creates a circular distance field with sinusoidal radial waves.
 *
 * @param uv         2D coordinate relative to the circle's center.
 * @param waveCount  Number of radial wave cycles around the circle.
 * @param waveHeight Amplitude of the radial displacement.
 * @param adjust     Phase offset applied to the angular pattern.
 * @return           Modified radial distance for the waved circle.
 */
float wavedCircleField(vec2 uv, float waveCount, float waveHeight, float adjust) {
    float angle = getAngle(uv) + adjust;
    float radius = sin(angle * PI * 2.0 * waveCount) * waveHeight;

    return circleField(uv) + radius;
}
